# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GSMCoverBuilder
                                 A QGIS plugin
 GSM Cover Builder allows you to quickly generate coverage plans based on localities and a defined coverage radius
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-11
        copyright            : (C) 2025 by Fadil Kristof GNANKAMBARY
        email                : krisfadil@live.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GSMCoverBuilder class from file GSMCoverBuilder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GSM_Cover_Builder import GSMCoverBuilder
    return GSMCoverBuilder(iface)
